<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api\TaskWorkerPartitionedStrategyInfo;

use UnexpectedValueException;

/**
 * Protobuf type <code>clarifai.api.TaskWorkerPartitionedStrategyInfo.TaskWorkerPartitionedStrategy</code>
 */
class TaskWorkerPartitionedStrategy
{
    /**
     * Generated from protobuf enum <code>PARTITIONED_WORKER_STRATEGY_NOT_SET = 0;</code>
     */
    const PARTITIONED_WORKER_STRATEGY_NOT_SET = 0;
    /**
     * Each worker will label (approximately) the same number of inputs.
     *
     * Generated from protobuf enum <code>EVENLY = 1;</code>
     */
    const EVENLY = 1;
    /**
     * Each worker will have an assigned weight.
     * See weights field for more details.
     *
     * Generated from protobuf enum <code>WEIGHTED = 2;</code>
     */
    const WEIGHTED = 2;

    private static $valueToName = [
        self::PARTITIONED_WORKER_STRATEGY_NOT_SET => 'PARTITIONED_WORKER_STRATEGY_NOT_SET',
        self::EVENLY => 'EVENLY',
        self::WEIGHTED => 'WEIGHTED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TaskWorkerPartitionedStrategy::class, \Clarifai\Api\TaskWorkerPartitionedStrategyInfo_TaskWorkerPartitionedStrategy::class);

