<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api\App;

use UnexpectedValueException;

/**
 * Protobuf type <code>clarifai.api.App.EmbeddingsStorage</code>
 */
class EmbeddingsStorage
{
    /**
     * Generated from protobuf enum <code>EMBEDDING_STORAGE_NOT_SET = 0;</code>
     */
    const EMBEDDING_STORAGE_NOT_SET = 0;
    /**
     * Generated from protobuf enum <code>POSTGRES = 1;</code>
     */
    const POSTGRES = 1;
    /**
     * Generated from protobuf enum <code>QDRANT = 2;</code>
     */
    const QDRANT = 2;

    private static $valueToName = [
        self::EMBEDDING_STORAGE_NOT_SET => 'EMBEDDING_STORAGE_NOT_SET',
        self::POSTGRES => 'POSTGRES',
        self::QDRANT => 'QDRANT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(EmbeddingsStorage::class, \Clarifai\Api\App_EmbeddingsStorage::class);

