<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api\ModuleVersion;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.ModuleVersion.ModuleSubNav</code>
 */
class ModuleSubNav extends \Google\Protobuf\Internal\Message
{
    /**
     * This is the display title for a navbar element to link to a specific page.
     * The name for this subnav element to show in the sidebar.
     *
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * The query param name
     *
     * Generated from protobuf field <code>string query_key = 2;</code>
     */
    protected $query_key = '';
    /**
     * The query param value
     *
     * Generated from protobuf field <code>string query_value = 3;</code>
     */
    protected $query_value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *           This is the display title for a navbar element to link to a specific page.
     *           The name for this subnav element to show in the sidebar.
     *     @type string $query_key
     *           The query param name
     *     @type string $query_value
     *           The query param value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * This is the display title for a navbar element to link to a specific page.
     * The name for this subnav element to show in the sidebar.
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * This is the display title for a navbar element to link to a specific page.
     * The name for this subnav element to show in the sidebar.
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * The query param name
     *
     * Generated from protobuf field <code>string query_key = 2;</code>
     * @return string
     */
    public function getQueryKey()
    {
        return $this->query_key;
    }

    /**
     * The query param name
     *
     * Generated from protobuf field <code>string query_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->query_key = $var;

        return $this;
    }

    /**
     * The query param value
     *
     * Generated from protobuf field <code>string query_value = 3;</code>
     * @return string
     */
    public function getQueryValue()
    {
        return $this->query_value;
    }

    /**
     * The query param value
     *
     * Generated from protobuf field <code>string query_value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->query_value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ModuleSubNav::class, \Clarifai\Api\ModuleVersion_ModuleSubNav::class);

