<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AiAssistParameters
 *
 * Generated from protobuf message <code>clarifai.api.AiAssistParameters</code>
 */
class AiAssistParameters extends \Google\Protobuf\Internal\Message
{
    /**
     * Min and max threshold values for approving annotations by default based on prediction score
     *
     * Generated from protobuf field <code>float min_threshold = 1;</code>
     */
    protected $min_threshold = 0.0;
    /**
     * Generated from protobuf field <code>float max_threshold = 2;</code>
     */
    protected $max_threshold = 0.0;
    /**
     * ids of concept relations. Used in AI assist workflow
     *
     * Generated from protobuf field <code>repeated string concept_relation_ids = 3;</code>
     */
    private $concept_relation_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $min_threshold
     *           Min and max threshold values for approving annotations by default based on prediction score
     *     @type float $max_threshold
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $concept_relation_ids
     *           ids of concept relations. Used in AI assist workflow
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Min and max threshold values for approving annotations by default based on prediction score
     *
     * Generated from protobuf field <code>float min_threshold = 1;</code>
     * @return float
     */
    public function getMinThreshold()
    {
        return $this->min_threshold;
    }

    /**
     * Min and max threshold values for approving annotations by default based on prediction score
     *
     * Generated from protobuf field <code>float min_threshold = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setMinThreshold($var)
    {
        GPBUtil::checkFloat($var);
        $this->min_threshold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float max_threshold = 2;</code>
     * @return float
     */
    public function getMaxThreshold()
    {
        return $this->max_threshold;
    }

    /**
     * Generated from protobuf field <code>float max_threshold = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxThreshold($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_threshold = $var;

        return $this;
    }

    /**
     * ids of concept relations. Used in AI assist workflow
     *
     * Generated from protobuf field <code>repeated string concept_relation_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConceptRelationIds()
    {
        return $this->concept_relation_ids;
    }

    /**
     * ids of concept relations. Used in AI assist workflow
     *
     * Generated from protobuf field <code>repeated string concept_relation_ids = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConceptRelationIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->concept_relation_ids = $arr;

        return $this;
    }

}

