<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AuditLogEntry is a single operation recorded in an audit log.
 *
 * Generated from protobuf message <code>clarifai.api.AuditLogEntry</code>
 */
class AuditLogEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Time of the operation.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    protected $timestamp = null;
    /**
     * User that performed the operation.
     *
     * Generated from protobuf field <code>.clarifai.api.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Type of operation that was performed.
     *
     * Generated from protobuf field <code>.clarifai.api.EventType operation = 3;</code>
     */
    protected $operation = 0;
    /**
     * A human-readable description of the operation.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Targets of the operation. For example,
     * - when creating a new model, the targets would be the application and the model,
     * - when adding a team member, the targets would be the team and the member.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.AuditLogTarget targets = 5;</code>
     */
    private $targets;
    /**
     * Additional human-readable details of the operation. For example,
     * when patching a resource, these would list what was changed.
     *
     * Generated from protobuf field <code>repeated string details = 6;</code>
     */
    private $details;
    /**
     * Was the operation successful?
     *
     * Generated from protobuf field <code>bool success = 7 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    protected $success = false;
    /**
     * Request that triggered the operation.
     *
     * Generated from protobuf field <code>string req_id = 8;</code>
     */
    protected $req_id = '';
    /**
     * IP address where the request originated from.
     *
     * Generated from protobuf field <code>string source_ip = 9;</code>
     */
    protected $source_ip = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $timestamp
     *           Time of the operation.
     *     @type \Clarifai\Api\User $user
     *           User that performed the operation.
     *     @type int $operation
     *           Type of operation that was performed.
     *     @type string $description
     *           A human-readable description of the operation.
     *     @type array<\Clarifai\Api\AuditLogTarget>|\Google\Protobuf\Internal\RepeatedField $targets
     *           Targets of the operation. For example,
     *           - when creating a new model, the targets would be the application and the model,
     *           - when adding a team member, the targets would be the team and the member.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $details
     *           Additional human-readable details of the operation. For example,
     *           when patching a resource, these would list what was changed.
     *     @type bool $success
     *           Was the operation successful?
     *     @type string $req_id
     *           Request that triggered the operation.
     *     @type string $source_ip
     *           IP address where the request originated from.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Time of the operation.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Time of the operation.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * User that performed the operation.
     *
     * Generated from protobuf field <code>.clarifai.api.User user = 2;</code>
     * @return \Clarifai\Api\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * User that performed the operation.
     *
     * Generated from protobuf field <code>.clarifai.api.User user = 2;</code>
     * @param \Clarifai\Api\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Type of operation that was performed.
     *
     * Generated from protobuf field <code>.clarifai.api.EventType operation = 3;</code>
     * @return int
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * Type of operation that was performed.
     *
     * Generated from protobuf field <code>.clarifai.api.EventType operation = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkEnum($var, \Clarifai\Api\EventType::class);
        $this->operation = $var;

        return $this;
    }

    /**
     * A human-readable description of the operation.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * A human-readable description of the operation.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Targets of the operation. For example,
     * - when creating a new model, the targets would be the application and the model,
     * - when adding a team member, the targets would be the team and the member.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.AuditLogTarget targets = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargets()
    {
        return $this->targets;
    }

    /**
     * Targets of the operation. For example,
     * - when creating a new model, the targets would be the application and the model,
     * - when adding a team member, the targets would be the team and the member.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.AuditLogTarget targets = 5;</code>
     * @param array<\Clarifai\Api\AuditLogTarget>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\AuditLogTarget::class);
        $this->targets = $arr;

        return $this;
    }

    /**
     * Additional human-readable details of the operation. For example,
     * when patching a resource, these would list what was changed.
     *
     * Generated from protobuf field <code>repeated string details = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Additional human-readable details of the operation. For example,
     * when patching a resource, these would list what was changed.
     *
     * Generated from protobuf field <code>repeated string details = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->details = $arr;

        return $this;
    }

    /**
     * Was the operation successful?
     *
     * Generated from protobuf field <code>bool success = 7 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Was the operation successful?
     *
     * Generated from protobuf field <code>bool success = 7 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Request that triggered the operation.
     *
     * Generated from protobuf field <code>string req_id = 8;</code>
     * @return string
     */
    public function getReqId()
    {
        return $this->req_id;
    }

    /**
     * Request that triggered the operation.
     *
     * Generated from protobuf field <code>string req_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setReqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->req_id = $var;

        return $this;
    }

    /**
     * IP address where the request originated from.
     *
     * Generated from protobuf field <code>string source_ip = 9;</code>
     * @return string
     */
    public function getSourceIp()
    {
        return $this->source_ip;
    }

    /**
     * IP address where the request originated from.
     *
     * Generated from protobuf field <code>string source_ip = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_ip = $var;

        return $this;
    }

}

