<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ConceptExtraInfo represents extra information related to a concept that is context-dependent.
 * It is only set when requested in ConceptExtraInfoRequest.
 *
 * Generated from protobuf message <code>clarifai.api.ConceptExtraInfo</code>
 */
class ConceptExtraInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether this concept is rankable based on ConceptExtraInfoRequest configuration.
     *
     * Generated from protobuf field <code>bool is_rankable = 1;</code>
     */
    protected $is_rankable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_rankable
     *           Whether this concept is rankable based on ConceptExtraInfoRequest configuration.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether this concept is rankable based on ConceptExtraInfoRequest configuration.
     *
     * Generated from protobuf field <code>bool is_rankable = 1;</code>
     * @return bool
     */
    public function getIsRankable()
    {
        return $this->is_rankable;
    }

    /**
     * Whether this concept is rankable based on ConceptExtraInfoRequest configuration.
     *
     * Generated from protobuf field <code>bool is_rankable = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRankable($var)
    {
        GPBUtil::checkBool($var);
        $this->is_rankable = $var;

        return $this;
    }

}

