<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * NOTE: this is inefficient, should just have the order of the rows/cols
 *
 * Generated from protobuf message <code>clarifai.api.CooccurrenceMatrixEntry</code>
 */
class CooccurrenceMatrixEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * concept_id for the row
     *
     * Generated from protobuf field <code>string row = 1;</code>
     */
    protected $row = '';
    /**
     * concept_id for the col
     *
     * Generated from protobuf field <code>string col = 2;</code>
     */
    protected $col = '';
    /**
     * Generated from protobuf field <code>uint32 count = 3;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $row
     *           concept_id for the row
     *     @type string $col
     *           concept_id for the col
     *     @type int $count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * concept_id for the row
     *
     * Generated from protobuf field <code>string row = 1;</code>
     * @return string
     */
    public function getRow()
    {
        return $this->row;
    }

    /**
     * concept_id for the row
     *
     * Generated from protobuf field <code>string row = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRow($var)
    {
        GPBUtil::checkString($var, True);
        $this->row = $var;

        return $this;
    }

    /**
     * concept_id for the col
     *
     * Generated from protobuf field <code>string col = 2;</code>
     * @return string
     */
    public function getCol()
    {
        return $this->col;
    }

    /**
     * concept_id for the col
     *
     * Generated from protobuf field <code>string col = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCol($var)
    {
        GPBUtil::checkString($var, True);
        $this->col = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

}

