<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * EvalTestSetEntry
 *
 * Generated from protobuf message <code>clarifai.api.EvalTestSetEntry</code>
 */
class EvalTestSetEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * the input information
     *
     * Generated from protobuf field <code>.clarifai.api.Input input = 6;</code>
     */
    protected $input = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept predicted_concepts = 3;</code>
     */
    private $predicted_concepts;
    /**
     * All the ground truth concepts will be show on the top level
     *
     * Generated from protobuf field <code>repeated .clarifai.api.Concept ground_truth_concepts = 4;</code>
     */
    private $ground_truth_concepts;
    /**
     * Only region-based/frame-based app contains this annotation
     * Each annotation only contains one region
     * And the concepts is in ground_truth_concepts instead of this annotation
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation annotation = 5 [deprecated = true];</code>
     * @deprecated
     */
    protected $annotation = null;
    /**
     * For region based models, region and associated concepts are stored together.
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation predicted_annotation = 7;</code>
     */
    protected $predicted_annotation = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Annotation ground_truth_annotation = 8;</code>
     */
    protected $ground_truth_annotation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\Input $input
     *           the input information
     *     @type array<\Clarifai\Api\Concept>|\Google\Protobuf\Internal\RepeatedField $predicted_concepts
     *     @type array<\Clarifai\Api\Concept>|\Google\Protobuf\Internal\RepeatedField $ground_truth_concepts
     *           All the ground truth concepts will be show on the top level
     *     @type \Clarifai\Api\Annotation $annotation
     *           Only region-based/frame-based app contains this annotation
     *           Each annotation only contains one region
     *           And the concepts is in ground_truth_concepts instead of this annotation
     *     @type \Clarifai\Api\Annotation $predicted_annotation
     *           For region based models, region and associated concepts are stored together.
     *     @type \Clarifai\Api\Annotation $ground_truth_annotation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * the input information
     *
     * Generated from protobuf field <code>.clarifai.api.Input input = 6;</code>
     * @return \Clarifai\Api\Input|null
     */
    public function getInput()
    {
        return $this->input;
    }

    public function hasInput()
    {
        return isset($this->input);
    }

    public function clearInput()
    {
        unset($this->input);
    }

    /**
     * the input information
     *
     * Generated from protobuf field <code>.clarifai.api.Input input = 6;</code>
     * @param \Clarifai\Api\Input $var
     * @return $this
     */
    public function setInput($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Input::class);
        $this->input = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept predicted_concepts = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPredictedConcepts()
    {
        return $this->predicted_concepts;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept predicted_concepts = 3;</code>
     * @param array<\Clarifai\Api\Concept>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPredictedConcepts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\Concept::class);
        $this->predicted_concepts = $arr;

        return $this;
    }

    /**
     * All the ground truth concepts will be show on the top level
     *
     * Generated from protobuf field <code>repeated .clarifai.api.Concept ground_truth_concepts = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroundTruthConcepts()
    {
        return $this->ground_truth_concepts;
    }

    /**
     * All the ground truth concepts will be show on the top level
     *
     * Generated from protobuf field <code>repeated .clarifai.api.Concept ground_truth_concepts = 4;</code>
     * @param array<\Clarifai\Api\Concept>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroundTruthConcepts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\Concept::class);
        $this->ground_truth_concepts = $arr;

        return $this;
    }

    /**
     * Only region-based/frame-based app contains this annotation
     * Each annotation only contains one region
     * And the concepts is in ground_truth_concepts instead of this annotation
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation annotation = 5 [deprecated = true];</code>
     * @return \Clarifai\Api\Annotation|null
     * @deprecated
     */
    public function getAnnotation()
    {
        @trigger_error('annotation is deprecated.', E_USER_DEPRECATED);
        return $this->annotation;
    }

    public function hasAnnotation()
    {
        @trigger_error('annotation is deprecated.', E_USER_DEPRECATED);
        return isset($this->annotation);
    }

    public function clearAnnotation()
    {
        @trigger_error('annotation is deprecated.', E_USER_DEPRECATED);
        unset($this->annotation);
    }

    /**
     * Only region-based/frame-based app contains this annotation
     * Each annotation only contains one region
     * And the concepts is in ground_truth_concepts instead of this annotation
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation annotation = 5 [deprecated = true];</code>
     * @param \Clarifai\Api\Annotation $var
     * @return $this
     * @deprecated
     */
    public function setAnnotation($var)
    {
        @trigger_error('annotation is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \Clarifai\Api\Annotation::class);
        $this->annotation = $var;

        return $this;
    }

    /**
     * For region based models, region and associated concepts are stored together.
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation predicted_annotation = 7;</code>
     * @return \Clarifai\Api\Annotation|null
     */
    public function getPredictedAnnotation()
    {
        return $this->predicted_annotation;
    }

    public function hasPredictedAnnotation()
    {
        return isset($this->predicted_annotation);
    }

    public function clearPredictedAnnotation()
    {
        unset($this->predicted_annotation);
    }

    /**
     * For region based models, region and associated concepts are stored together.
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation predicted_annotation = 7;</code>
     * @param \Clarifai\Api\Annotation $var
     * @return $this
     */
    public function setPredictedAnnotation($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Annotation::class);
        $this->predicted_annotation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Annotation ground_truth_annotation = 8;</code>
     * @return \Clarifai\Api\Annotation|null
     */
    public function getGroundTruthAnnotation()
    {
        return $this->ground_truth_annotation;
    }

    public function hasGroundTruthAnnotation()
    {
        return isset($this->ground_truth_annotation);
    }

    public function clearGroundTruthAnnotation()
    {
        unset($this->ground_truth_annotation);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Annotation ground_truth_annotation = 8;</code>
     * @param \Clarifai\Api\Annotation $var
     * @return $this
     */
    public function setGroundTruthAnnotation($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Annotation::class);
        $this->ground_truth_annotation = $var;

        return $this;
    }

}

