<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use UnexpectedValueException;

/**
 * Protobuf type <code>clarifai.api.ExpirationAction</code>
 */
class ExpirationAction
{
    /**
     * Generated from protobuf enum <code>EXPIRATION_ACTION_NOT_SET = 0;</code>
     */
    const EXPIRATION_ACTION_NOT_SET = 0;
    /**
     * Progressively delay the execution of operations
     *
     * Generated from protobuf enum <code>DELAY = 1;</code>
     */
    const DELAY = 1;
    /**
     * Cease functioning
     *
     * Generated from protobuf enum <code>EXPIRY = 2;</code>
     */
    const EXPIRY = 2;

    private static $valueToName = [
        self::EXPIRATION_ACTION_NOT_SET => 'EXPIRATION_ACTION_NOT_SET',
        self::DELAY => 'DELAY',
        self::EXPIRY => 'EXPIRY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

