<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Filter
 *
 * Generated from protobuf message <code>clarifai.api.Filter</code>
 */
class Filter extends \Google\Protobuf\Internal\Message
{
    /**
     * If True then this will flip the meaning of this part of the
     * query. This allow for queries such as dog AND ! metadata=={"blah":"value"}
     *
     * Generated from protobuf field <code>bool negate = 3;</code>
     */
    protected $negate = false;
    /**
     * FILTER by annotation information.
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation annotation = 4;</code>
     */
    protected $annotation = null;
    /**
     * FILTER by input information.
     * For example you can filter inputs by status,
     *
     * Generated from protobuf field <code>.clarifai.api.Input input = 5;</code>
     */
    protected $input = null;
    /**
     * Filter by annotation last updated time range.
     *
     * Generated from protobuf field <code>.clarifai.api.TimeRange last_updated_time_range = 6;</code>
     */
    protected $last_updated_time_range = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $negate
     *           If True then this will flip the meaning of this part of the
     *           query. This allow for queries such as dog AND ! metadata=={"blah":"value"}
     *     @type \Clarifai\Api\Annotation $annotation
     *           FILTER by annotation information.
     *     @type \Clarifai\Api\Input $input
     *           FILTER by input information.
     *           For example you can filter inputs by status,
     *     @type \Clarifai\Api\TimeRange $last_updated_time_range
     *           Filter by annotation last updated time range.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * If True then this will flip the meaning of this part of the
     * query. This allow for queries such as dog AND ! metadata=={"blah":"value"}
     *
     * Generated from protobuf field <code>bool negate = 3;</code>
     * @return bool
     */
    public function getNegate()
    {
        return $this->negate;
    }

    /**
     * If True then this will flip the meaning of this part of the
     * query. This allow for queries such as dog AND ! metadata=={"blah":"value"}
     *
     * Generated from protobuf field <code>bool negate = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setNegate($var)
    {
        GPBUtil::checkBool($var);
        $this->negate = $var;

        return $this;
    }

    /**
     * FILTER by annotation information.
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation annotation = 4;</code>
     * @return \Clarifai\Api\Annotation|null
     */
    public function getAnnotation()
    {
        return $this->annotation;
    }

    public function hasAnnotation()
    {
        return isset($this->annotation);
    }

    public function clearAnnotation()
    {
        unset($this->annotation);
    }

    /**
     * FILTER by annotation information.
     *
     * Generated from protobuf field <code>.clarifai.api.Annotation annotation = 4;</code>
     * @param \Clarifai\Api\Annotation $var
     * @return $this
     */
    public function setAnnotation($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Annotation::class);
        $this->annotation = $var;

        return $this;
    }

    /**
     * FILTER by input information.
     * For example you can filter inputs by status,
     *
     * Generated from protobuf field <code>.clarifai.api.Input input = 5;</code>
     * @return \Clarifai\Api\Input|null
     */
    public function getInput()
    {
        return $this->input;
    }

    public function hasInput()
    {
        return isset($this->input);
    }

    public function clearInput()
    {
        unset($this->input);
    }

    /**
     * FILTER by input information.
     * For example you can filter inputs by status,
     *
     * Generated from protobuf field <code>.clarifai.api.Input input = 5;</code>
     * @param \Clarifai\Api\Input $var
     * @return $this
     */
    public function setInput($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Input::class);
        $this->input = $var;

        return $this;
    }

    /**
     * Filter by annotation last updated time range.
     *
     * Generated from protobuf field <code>.clarifai.api.TimeRange last_updated_time_range = 6;</code>
     * @return \Clarifai\Api\TimeRange|null
     */
    public function getLastUpdatedTimeRange()
    {
        return $this->last_updated_time_range;
    }

    public function hasLastUpdatedTimeRange()
    {
        return isset($this->last_updated_time_range);
    }

    public function clearLastUpdatedTimeRange()
    {
        unset($this->last_updated_time_range);
    }

    /**
     * Filter by annotation last updated time range.
     *
     * Generated from protobuf field <code>.clarifai.api.TimeRange last_updated_time_range = 6;</code>
     * @param \Clarifai\Api\TimeRange $var
     * @return $this
     */
    public function setLastUpdatedTimeRange($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\TimeRange::class);
        $this->last_updated_time_range = $var;

        return $this;
    }

}

