<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The information of the location of the Frame.
 *
 * Generated from protobuf message <code>clarifai.api.FrameInfo</code>
 */
class FrameInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Deprecated. Use Time instead.
     * The index of the frame, informational and optional.
     * Depends on the sampling rate used during processing
     * May be 0 for interpolated frames that are generated for brief time (training) or if new frame is manually added
     *
     * Generated from protobuf field <code>uint32 index = 1 [deprecated = true, (.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @deprecated
     */
    protected $index = 0;
    /**
     * time in the video in milliseconds. This is independent of the sampling rates used during
     * processing.
     *
     * Generated from protobuf field <code>uint32 time = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    protected $time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $index
     *           Deprecated. Use Time instead.
     *           The index of the frame, informational and optional.
     *           Depends on the sampling rate used during processing
     *           May be 0 for interpolated frames that are generated for brief time (training) or if new frame is manually added
     *     @type int $time
     *           time in the video in milliseconds. This is independent of the sampling rates used during
     *           processing.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Deprecated. Use Time instead.
     * The index of the frame, informational and optional.
     * Depends on the sampling rate used during processing
     * May be 0 for interpolated frames that are generated for brief time (training) or if new frame is manually added
     *
     * Generated from protobuf field <code>uint32 index = 1 [deprecated = true, (.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return int
     * @deprecated
     */
    public function getIndex()
    {
        @trigger_error('index is deprecated.', E_USER_DEPRECATED);
        return $this->index;
    }

    /**
     * Deprecated. Use Time instead.
     * The index of the frame, informational and optional.
     * Depends on the sampling rate used during processing
     * May be 0 for interpolated frames that are generated for brief time (training) or if new frame is manually added
     *
     * Generated from protobuf field <code>uint32 index = 1 [deprecated = true, (.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setIndex($var)
    {
        @trigger_error('index is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * time in the video in milliseconds. This is independent of the sampling rates used during
     * processing.
     *
     * Generated from protobuf field <code>uint32 time = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return int
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * time in the video in milliseconds. This is independent of the sampling rates used during
     * processing.
     *
     * Generated from protobuf field <code>uint32 time = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param int $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->time = $var;

        return $this;
    }

}

