<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.InputSettings</code>
 */
class InputSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Default model used for annotation generation (SAM2, etc.)
     * Make sure to set correct model version id, app id and user id etc.
     * Workflow is not supported here yet
     *
     * Generated from protobuf field <code>.clarifai.api.Worker worker = 1;</code>
     */
    protected $worker = null;
    /**
     * Sampling settings used
     *
     * Generated from protobuf field <code>uint32 sample_rate_ms = 2;</code>
     */
    protected $sample_rate_ms = 0;
    /**
     * Generated from protobuf field <code>uint32 sample_rate_frame = 3;</code>
     */
    protected $sample_rate_frame = 0;
    /**
     * Pinned concept ids
     *
     * Generated from protobuf field <code>repeated string pinned_concept_ids = 4;</code>
     */
    private $pinned_concept_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\Worker $worker
     *           Default model used for annotation generation (SAM2, etc.)
     *           Make sure to set correct model version id, app id and user id etc.
     *           Workflow is not supported here yet
     *     @type int $sample_rate_ms
     *           Sampling settings used
     *     @type int $sample_rate_frame
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $pinned_concept_ids
     *           Pinned concept ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Default model used for annotation generation (SAM2, etc.)
     * Make sure to set correct model version id, app id and user id etc.
     * Workflow is not supported here yet
     *
     * Generated from protobuf field <code>.clarifai.api.Worker worker = 1;</code>
     * @return \Clarifai\Api\Worker|null
     */
    public function getWorker()
    {
        return $this->worker;
    }

    public function hasWorker()
    {
        return isset($this->worker);
    }

    public function clearWorker()
    {
        unset($this->worker);
    }

    /**
     * Default model used for annotation generation (SAM2, etc.)
     * Make sure to set correct model version id, app id and user id etc.
     * Workflow is not supported here yet
     *
     * Generated from protobuf field <code>.clarifai.api.Worker worker = 1;</code>
     * @param \Clarifai\Api\Worker $var
     * @return $this
     */
    public function setWorker($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Worker::class);
        $this->worker = $var;

        return $this;
    }

    /**
     * Sampling settings used
     *
     * Generated from protobuf field <code>uint32 sample_rate_ms = 2;</code>
     * @return int
     */
    public function getSampleRateMs()
    {
        return $this->sample_rate_ms;
    }

    /**
     * Sampling settings used
     *
     * Generated from protobuf field <code>uint32 sample_rate_ms = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSampleRateMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->sample_rate_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sample_rate_frame = 3;</code>
     * @return int
     */
    public function getSampleRateFrame()
    {
        return $this->sample_rate_frame;
    }

    /**
     * Generated from protobuf field <code>uint32 sample_rate_frame = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSampleRateFrame($var)
    {
        GPBUtil::checkUint32($var);
        $this->sample_rate_frame = $var;

        return $this;
    }

    /**
     * Pinned concept ids
     *
     * Generated from protobuf field <code>repeated string pinned_concept_ids = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPinnedConceptIds()
    {
        return $this->pinned_concept_ids;
    }

    /**
     * Pinned concept ids
     *
     * Generated from protobuf field <code>repeated string pinned_concept_ids = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPinnedConceptIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pinned_concept_ids = $arr;

        return $this;
    }

}

