<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A Knowledge Graph is a logical subsets of edges in the overall Concept Graph
 *
 * Generated from protobuf message <code>clarifai.api.KnowledgeGraph</code>
 */
class KnowledgeGraph extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the knowledge graph
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Name of the knowledge graph
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Human readable description of the knowledge graph
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * The app that contains the images that correspond to the concepts in the knowledge graph
     *
     * Generated from protobuf field <code>string examples_app_id = 4;</code>
     */
    protected $examples_app_id = '';
    /**
     * The app that contains the sample images that we want to show the customer for the concepts in the knowledge graph
     *
     * Generated from protobuf field <code>string sampled_examples_app_id = 5;</code>
     */
    protected $sampled_examples_app_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           ID of the knowledge graph
     *     @type string $name
     *           Name of the knowledge graph
     *     @type string $description
     *           Human readable description of the knowledge graph
     *     @type string $examples_app_id
     *           The app that contains the images that correspond to the concepts in the knowledge graph
     *     @type string $sampled_examples_app_id
     *           The app that contains the sample images that we want to show the customer for the concepts in the knowledge graph
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the knowledge graph
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * ID of the knowledge graph
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Name of the knowledge graph
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the knowledge graph
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Human readable description of the knowledge graph
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Human readable description of the knowledge graph
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * The app that contains the images that correspond to the concepts in the knowledge graph
     *
     * Generated from protobuf field <code>string examples_app_id = 4;</code>
     * @return string
     */
    public function getExamplesAppId()
    {
        return $this->examples_app_id;
    }

    /**
     * The app that contains the images that correspond to the concepts in the knowledge graph
     *
     * Generated from protobuf field <code>string examples_app_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExamplesAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->examples_app_id = $var;

        return $this;
    }

    /**
     * The app that contains the sample images that we want to show the customer for the concepts in the knowledge graph
     *
     * Generated from protobuf field <code>string sampled_examples_app_id = 5;</code>
     * @return string
     */
    public function getSampledExamplesAppId()
    {
        return $this->sampled_examples_app_id;
    }

    /**
     * The app that contains the sample images that we want to show the customer for the concepts in the knowledge graph
     *
     * Generated from protobuf field <code>string sampled_examples_app_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSampledExamplesAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sampled_examples_app_id = $var;

        return $this;
    }

}

