<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ListKeysRequest
 *
 * Generated from protobuf message <code>clarifai.api.ListKeysRequest</code>
 */
class ListKeysRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    protected $user_app_id = null;
    /**
     * (optional URL parameter) The page number. Pagination is used to split the results into chunks.
     * Defaults to 1.
     *
     * Generated from protobuf field <code>uint32 page = 2;</code>
     */
    protected $page = 0;
    /**
     * (optional URL parameter) The number of results that will be contained in each page. Defaults
     * to 128.
     *
     * Generated from protobuf field <code>uint32 per_page = 3;</code>
     */
    protected $per_page = 0;
    /**
     * Filtering options:
     * If true, only return keys that have not expired.
     *
     * Generated from protobuf field <code>bool not_expired = 4;</code>
     */
    protected $not_expired = false;
    /**
     * Only return keys that have the listed scopes.
     *
     * Generated from protobuf field <code>repeated string scopes = 5;</code>
     */
    private $scopes;
    /**
     * Only return keys that have the listed endpoints.
     *
     * Generated from protobuf field <code>repeated string endpoints = 6;</code>
     */
    private $endpoints;
    /**
     * Only return keys with the listed type.
     *
     * Generated from protobuf field <code>string type = 7;</code>
     */
    protected $type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\UserAppIDSet $user_app_id
     *     @type int $page
     *           (optional URL parameter) The page number. Pagination is used to split the results into chunks.
     *           Defaults to 1.
     *     @type int $per_page
     *           (optional URL parameter) The number of results that will be contained in each page. Defaults
     *           to 128.
     *     @type bool $not_expired
     *           Filtering options:
     *           If true, only return keys that have not expired.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $scopes
     *           Only return keys that have the listed scopes.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $endpoints
     *           Only return keys that have the listed endpoints.
     *     @type string $type
     *           Only return keys with the listed type.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return \Clarifai\Api\UserAppIDSet|null
     */
    public function getUserAppId()
    {
        return $this->user_app_id;
    }

    public function hasUserAppId()
    {
        return isset($this->user_app_id);
    }

    public function clearUserAppId()
    {
        unset($this->user_app_id);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @param \Clarifai\Api\UserAppIDSet $var
     * @return $this
     */
    public function setUserAppId($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\UserAppIDSet::class);
        $this->user_app_id = $var;

        return $this;
    }

    /**
     * (optional URL parameter) The page number. Pagination is used to split the results into chunks.
     * Defaults to 1.
     *
     * Generated from protobuf field <code>uint32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * (optional URL parameter) The page number. Pagination is used to split the results into chunks.
     * Defaults to 1.
     *
     * Generated from protobuf field <code>uint32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * (optional URL parameter) The number of results that will be contained in each page. Defaults
     * to 128.
     *
     * Generated from protobuf field <code>uint32 per_page = 3;</code>
     * @return int
     */
    public function getPerPage()
    {
        return $this->per_page;
    }

    /**
     * (optional URL parameter) The number of results that will be contained in each page. Defaults
     * to 128.
     *
     * Generated from protobuf field <code>uint32 per_page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPerPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->per_page = $var;

        return $this;
    }

    /**
     * Filtering options:
     * If true, only return keys that have not expired.
     *
     * Generated from protobuf field <code>bool not_expired = 4;</code>
     * @return bool
     */
    public function getNotExpired()
    {
        return $this->not_expired;
    }

    /**
     * Filtering options:
     * If true, only return keys that have not expired.
     *
     * Generated from protobuf field <code>bool not_expired = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotExpired($var)
    {
        GPBUtil::checkBool($var);
        $this->not_expired = $var;

        return $this;
    }

    /**
     * Only return keys that have the listed scopes.
     *
     * Generated from protobuf field <code>repeated string scopes = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * Only return keys that have the listed scopes.
     *
     * Generated from protobuf field <code>repeated string scopes = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scopes = $arr;

        return $this;
    }

    /**
     * Only return keys that have the listed endpoints.
     *
     * Generated from protobuf field <code>repeated string endpoints = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEndpoints()
    {
        return $this->endpoints;
    }

    /**
     * Only return keys that have the listed endpoints.
     *
     * Generated from protobuf field <code>repeated string endpoints = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEndpoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->endpoints = $arr;

        return $this;
    }

    /**
     * Only return keys with the listed type.
     *
     * Generated from protobuf field <code>string type = 7;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Only return keys with the listed type.
     *
     * Generated from protobuf field <code>string type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

}

