<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ListUserCyclesRequest
 *
 * Generated from protobuf message <code>clarifai.api.ListUserCyclesRequest</code>
 */
class ListUserCyclesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    protected $user_app_id = null;
    /**
     * (optional URL parameter) The number of cycles that will be contained in the response
     * Defaults to 12.
     *
     * Generated from protobuf field <code>uint32 cycle_number = 2;</code>
     */
    protected $cycle_number = 0;
    /**
     * (optional URL parameter) Get the cycles before and including this date
     * Defaults to now
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp before_date = 3;</code>
     */
    protected $before_date = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\UserAppIDSet $user_app_id
     *     @type int $cycle_number
     *           (optional URL parameter) The number of cycles that will be contained in the response
     *           Defaults to 12.
     *     @type \Google\Protobuf\Timestamp $before_date
     *           (optional URL parameter) Get the cycles before and including this date
     *           Defaults to now
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return \Clarifai\Api\UserAppIDSet|null
     */
    public function getUserAppId()
    {
        return $this->user_app_id;
    }

    public function hasUserAppId()
    {
        return isset($this->user_app_id);
    }

    public function clearUserAppId()
    {
        unset($this->user_app_id);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @param \Clarifai\Api\UserAppIDSet $var
     * @return $this
     */
    public function setUserAppId($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\UserAppIDSet::class);
        $this->user_app_id = $var;

        return $this;
    }

    /**
     * (optional URL parameter) The number of cycles that will be contained in the response
     * Defaults to 12.
     *
     * Generated from protobuf field <code>uint32 cycle_number = 2;</code>
     * @return int
     */
    public function getCycleNumber()
    {
        return $this->cycle_number;
    }

    /**
     * (optional URL parameter) The number of cycles that will be contained in the response
     * Defaults to 12.
     *
     * Generated from protobuf field <code>uint32 cycle_number = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCycleNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->cycle_number = $var;

        return $this;
    }

    /**
     * (optional URL parameter) Get the cycles before and including this date
     * Defaults to now
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp before_date = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getBeforeDate()
    {
        return $this->before_date;
    }

    public function hasBeforeDate()
    {
        return isset($this->before_date);
    }

    public function clearBeforeDate()
    {
        unset($this->before_date);
    }

    /**
     * (optional URL parameter) Get the cycles before and including this date
     * Defaults to now
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp before_date = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setBeforeDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->before_date = $var;

        return $this;
    }

}

