<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ModelTypeField stores a field value of a configurable type.
 *
 * Generated from protobuf message <code>clarifai.api.ModelTypeField</code>
 */
class ModelTypeField extends \Google\Protobuf\Internal\Message
{
    /**
     * The path where the value of the field will be stored.
     * Example:
     * "output_info.data" would be the Data message in the OutputInfo message.
     * "output_info.output_config.language" is in the OutputConfig message within OutputInfo
     * "input_info.params" is in the params struct within InputInfo.
     * "output_info.params" is in the params struct within OutputInfo.
     * "train_info.params" is in the params struct within TrainInfo.
     * and so on.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * The field for this field.
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeField.ModelTypeFieldType field_type = 2;</code>
     */
    protected $field_type = 0;
    /**
     * A default value. We use the Value field because we want to have structured data (just like
     * google.protobuf.Struct but this is just a single value).
     *
     * Generated from protobuf field <code>.google.protobuf.Value default_value = 3;</code>
     */
    protected $default_value = null;
    /**
     * Description for this field.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Placeholder text for the UI element.
     *
     * Generated from protobuf field <code>string placeholder = 5;</code>
     */
    protected $placeholder = '';
    /**
     * List of options of the ENUM type and potentially additional fields they bring with them.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.ModelTypeEnumOption model_type_enum_options = 6;</code>
     */
    private $model_type_enum_options;
    /**
     * If this field should appear for internal users only.
     *
     * Generated from protobuf field <code>bool internal_only = 7;</code>
     */
    protected $internal_only = false;
    /**
     * If this field is a required field. If True then during validation you won't be able to create
     * a model of this type with providing a value for this field. When False, the ModelType's
     * default_value will be used for this field.
     *
     * Generated from protobuf field <code>bool required = 8;</code>
     */
    protected $required = false;
    /**
     * If the field_type is RANGE, this must be filled in.
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeRangeInfo model_type_range_info = 9;</code>
     */
    protected $model_type_range_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           The path where the value of the field will be stored.
     *           Example:
     *           "output_info.data" would be the Data message in the OutputInfo message.
     *           "output_info.output_config.language" is in the OutputConfig message within OutputInfo
     *           "input_info.params" is in the params struct within InputInfo.
     *           "output_info.params" is in the params struct within OutputInfo.
     *           "train_info.params" is in the params struct within TrainInfo.
     *           and so on.
     *     @type int $field_type
     *           The field for this field.
     *     @type \Google\Protobuf\Value $default_value
     *           A default value. We use the Value field because we want to have structured data (just like
     *           google.protobuf.Struct but this is just a single value).
     *     @type string $description
     *           Description for this field.
     *     @type string $placeholder
     *           Placeholder text for the UI element.
     *     @type \Clarifai\Api\ModelTypeEnumOption[]|\Google\Protobuf\Internal\RepeatedField $model_type_enum_options
     *           List of options of the ENUM type and potentially additional fields they bring with them.
     *     @type bool $internal_only
     *           If this field should appear for internal users only.
     *     @type bool $required
     *           If this field is a required field. If True then during validation you won't be able to create
     *           a model of this type with providing a value for this field. When False, the ModelType's
     *           default_value will be used for this field.
     *     @type \Clarifai\Api\ModelTypeRangeInfo $model_type_range_info
     *           If the field_type is RANGE, this must be filled in.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * The path where the value of the field will be stored.
     * Example:
     * "output_info.data" would be the Data message in the OutputInfo message.
     * "output_info.output_config.language" is in the OutputConfig message within OutputInfo
     * "input_info.params" is in the params struct within InputInfo.
     * "output_info.params" is in the params struct within OutputInfo.
     * "train_info.params" is in the params struct within TrainInfo.
     * and so on.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * The path where the value of the field will be stored.
     * Example:
     * "output_info.data" would be the Data message in the OutputInfo message.
     * "output_info.output_config.language" is in the OutputConfig message within OutputInfo
     * "input_info.params" is in the params struct within InputInfo.
     * "output_info.params" is in the params struct within OutputInfo.
     * "train_info.params" is in the params struct within TrainInfo.
     * and so on.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * The field for this field.
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeField.ModelTypeFieldType field_type = 2;</code>
     * @return int
     */
    public function getFieldType()
    {
        return $this->field_type;
    }

    /**
     * The field for this field.
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeField.ModelTypeFieldType field_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldType($var)
    {
        GPBUtil::checkEnum($var, \Clarifai\Api\ModelTypeField\ModelTypeFieldType::class);
        $this->field_type = $var;

        return $this;
    }

    /**
     * A default value. We use the Value field because we want to have structured data (just like
     * google.protobuf.Struct but this is just a single value).
     *
     * Generated from protobuf field <code>.google.protobuf.Value default_value = 3;</code>
     * @return \Google\Protobuf\Value|null
     */
    public function getDefaultValue()
    {
        return $this->default_value;
    }

    public function hasDefaultValue()
    {
        return isset($this->default_value);
    }

    public function clearDefaultValue()
    {
        unset($this->default_value);
    }

    /**
     * A default value. We use the Value field because we want to have structured data (just like
     * google.protobuf.Struct but this is just a single value).
     *
     * Generated from protobuf field <code>.google.protobuf.Value default_value = 3;</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setDefaultValue($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->default_value = $var;

        return $this;
    }

    /**
     * Description for this field.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Description for this field.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Placeholder text for the UI element.
     *
     * Generated from protobuf field <code>string placeholder = 5;</code>
     * @return string
     */
    public function getPlaceholder()
    {
        return $this->placeholder;
    }

    /**
     * Placeholder text for the UI element.
     *
     * Generated from protobuf field <code>string placeholder = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceholder($var)
    {
        GPBUtil::checkString($var, True);
        $this->placeholder = $var;

        return $this;
    }

    /**
     * List of options of the ENUM type and potentially additional fields they bring with them.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.ModelTypeEnumOption model_type_enum_options = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModelTypeEnumOptions()
    {
        return $this->model_type_enum_options;
    }

    /**
     * List of options of the ENUM type and potentially additional fields they bring with them.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.ModelTypeEnumOption model_type_enum_options = 6;</code>
     * @param \Clarifai\Api\ModelTypeEnumOption[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModelTypeEnumOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\ModelTypeEnumOption::class);
        $this->model_type_enum_options = $arr;

        return $this;
    }

    /**
     * If this field should appear for internal users only.
     *
     * Generated from protobuf field <code>bool internal_only = 7;</code>
     * @return bool
     */
    public function getInternalOnly()
    {
        return $this->internal_only;
    }

    /**
     * If this field should appear for internal users only.
     *
     * Generated from protobuf field <code>bool internal_only = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setInternalOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->internal_only = $var;

        return $this;
    }

    /**
     * If this field is a required field. If True then during validation you won't be able to create
     * a model of this type with providing a value for this field. When False, the ModelType's
     * default_value will be used for this field.
     *
     * Generated from protobuf field <code>bool required = 8;</code>
     * @return bool
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * If this field is a required field. If True then during validation you won't be able to create
     * a model of this type with providing a value for this field. When False, the ModelType's
     * default_value will be used for this field.
     *
     * Generated from protobuf field <code>bool required = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->required = $var;

        return $this;
    }

    /**
     * If the field_type is RANGE, this must be filled in.
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeRangeInfo model_type_range_info = 9;</code>
     * @return \Clarifai\Api\ModelTypeRangeInfo|null
     */
    public function getModelTypeRangeInfo()
    {
        return $this->model_type_range_info;
    }

    public function hasModelTypeRangeInfo()
    {
        return isset($this->model_type_range_info);
    }

    public function clearModelTypeRangeInfo()
    {
        unset($this->model_type_range_info);
    }

    /**
     * If the field_type is RANGE, this must be filled in.
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeRangeInfo model_type_range_info = 9;</code>
     * @param \Clarifai\Api\ModelTypeRangeInfo $var
     * @return $this
     */
    public function setModelTypeRangeInfo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\ModelTypeRangeInfo::class);
        $this->model_type_range_info = $var;

        return $this;
    }

}

