<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MultiModelTypeResponse
 *
 * Generated from protobuf message <code>clarifai.api.MultiModelTypeResponse</code>
 */
class MultiModelTypeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Status of the response.
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * List of ModelType objects.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.ModelType model_types = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $model_types;
    /**
     * List of model importers
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeField model_importers = 3;</code>
     */
    protected $model_importers = null;
    /**
     * Triton model envs that can be used for model upload
     *
     * Generated from protobuf field <code>repeated .clarifai.api.TritonCondaEnvInfo triton_conda_envs_info = 4;</code>
     */
    private $triton_conda_envs_info;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\Status\Status $status
     *           Status of the response.
     *     @type array<\Clarifai\Api\ModelType>|\Google\Protobuf\Internal\RepeatedField $model_types
     *           List of ModelType objects.
     *     @type \Clarifai\Api\ModelTypeField $model_importers
     *           List of model importers
     *     @type array<\Clarifai\Api\TritonCondaEnvInfo>|\Google\Protobuf\Internal\RepeatedField $triton_conda_envs_info
     *           Triton model envs that can be used for model upload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Status of the response.
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Api\Status\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Status of the response.
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Api\Status\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Status\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * List of ModelType objects.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.ModelType model_types = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModelTypes()
    {
        return $this->model_types;
    }

    /**
     * List of ModelType objects.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.ModelType model_types = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param array<\Clarifai\Api\ModelType>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModelTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\ModelType::class);
        $this->model_types = $arr;

        return $this;
    }

    /**
     * List of model importers
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeField model_importers = 3;</code>
     * @return \Clarifai\Api\ModelTypeField|null
     */
    public function getModelImporters()
    {
        return $this->model_importers;
    }

    public function hasModelImporters()
    {
        return isset($this->model_importers);
    }

    public function clearModelImporters()
    {
        unset($this->model_importers);
    }

    /**
     * List of model importers
     *
     * Generated from protobuf field <code>.clarifai.api.ModelTypeField model_importers = 3;</code>
     * @param \Clarifai\Api\ModelTypeField $var
     * @return $this
     */
    public function setModelImporters($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\ModelTypeField::class);
        $this->model_importers = $var;

        return $this;
    }

    /**
     * Triton model envs that can be used for model upload
     *
     * Generated from protobuf field <code>repeated .clarifai.api.TritonCondaEnvInfo triton_conda_envs_info = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTritonCondaEnvsInfo()
    {
        return $this->triton_conda_envs_info;
    }

    /**
     * Triton model envs that can be used for model upload
     *
     * Generated from protobuf field <code>repeated .clarifai.api.TritonCondaEnvInfo triton_conda_envs_info = 4;</code>
     * @param array<\Clarifai\Api\TritonCondaEnvInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTritonCondaEnvsInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\TritonCondaEnvInfo::class);
        $this->triton_conda_envs_info = $arr;

        return $this;
    }

}

