<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MultiAnnotationSearchMetricsResponse
 *
 * Generated from protobuf message <code>clarifai.api.MultiAnnotationSearchMetricsResponse</code>
 */
class MultiAnnotationSearchMetricsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Status of the request
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.AnnotationSearchMetrics annotation_search_metrics = 2;</code>
     */
    private $annotation_search_metrics;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\Status\Status $status
     *           Status of the request
     *     @type array<\Clarifai\Api\AnnotationSearchMetrics>|\Google\Protobuf\Internal\RepeatedField $annotation_search_metrics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Status of the request
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Api\Status\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Status of the request
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Api\Status\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Status\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.AnnotationSearchMetrics annotation_search_metrics = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAnnotationSearchMetrics()
    {
        return $this->annotation_search_metrics;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.AnnotationSearchMetrics annotation_search_metrics = 2;</code>
     * @param array<\Clarifai\Api\AnnotationSearchMetrics>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAnnotationSearchMetrics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\AnnotationSearchMetrics::class);
        $this->annotation_search_metrics = $arr;

        return $this;
    }

}

