<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * NodepoolDeploymentMetrics captures metrics for a single nodepool within a Deployment.
 *
 * Generated from protobuf message <code>clarifai.api.NodepoolDeploymentMetrics</code>
 */
class NodepoolDeploymentMetrics extends \Google\Protobuf\Internal\Message
{
    /**
     * The user-facing compute cluster ID.
     *
     * Generated from protobuf field <code>string compute_cluster_id = 1;</code>
     */
    protected $compute_cluster_id = '';
    /**
     * The user-facing nodepool ID.
     *
     * Generated from protobuf field <code>string nodepool_id = 2;</code>
     */
    protected $nodepool_id = '';
    /**
     * Metrics for this nodepool.
     *
     * Generated from protobuf field <code>.clarifai.api.DeploymentMetricsSummary metrics = 3;</code>
     */
    protected $metrics = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $compute_cluster_id
     *           The user-facing compute cluster ID.
     *     @type string $nodepool_id
     *           The user-facing nodepool ID.
     *     @type \Clarifai\Api\DeploymentMetricsSummary $metrics
     *           Metrics for this nodepool.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * The user-facing compute cluster ID.
     *
     * Generated from protobuf field <code>string compute_cluster_id = 1;</code>
     * @return string
     */
    public function getComputeClusterId()
    {
        return $this->compute_cluster_id;
    }

    /**
     * The user-facing compute cluster ID.
     *
     * Generated from protobuf field <code>string compute_cluster_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setComputeClusterId($var)
    {
        GPBUtil::checkString($var, True);
        $this->compute_cluster_id = $var;

        return $this;
    }

    /**
     * The user-facing nodepool ID.
     *
     * Generated from protobuf field <code>string nodepool_id = 2;</code>
     * @return string
     */
    public function getNodepoolId()
    {
        return $this->nodepool_id;
    }

    /**
     * The user-facing nodepool ID.
     *
     * Generated from protobuf field <code>string nodepool_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNodepoolId($var)
    {
        GPBUtil::checkString($var, True);
        $this->nodepool_id = $var;

        return $this;
    }

    /**
     * Metrics for this nodepool.
     *
     * Generated from protobuf field <code>.clarifai.api.DeploymentMetricsSummary metrics = 3;</code>
     * @return \Clarifai\Api\DeploymentMetricsSummary|null
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    public function hasMetrics()
    {
        return isset($this->metrics);
    }

    public function clearMetrics()
    {
        unset($this->metrics);
    }

    /**
     * Metrics for this nodepool.
     *
     * Generated from protobuf field <code>.clarifai.api.DeploymentMetricsSummary metrics = 3;</code>
     * @param \Clarifai\Api\DeploymentMetricsSummary $var
     * @return $this
     */
    public function setMetrics($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\DeploymentMetricsSummary::class);
        $this->metrics = $var;

        return $this;
    }

}

