<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * NodeInput represents inputs to a node of the graph.
 *
 * Generated from protobuf message <code>clarifai.api.NodeInput</code>
 */
class NodeInput extends \Google\Protobuf\Internal\Message
{
    /**
     * The id to a connected WorkflowNode which will be used as an input for current WorkflowNode.
     *
     * Generated from protobuf field <code>string node_id = 1;</code>
     */
    protected $node_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $node_id
     *           The id to a connected WorkflowNode which will be used as an input for current WorkflowNode.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * The id to a connected WorkflowNode which will be used as an input for current WorkflowNode.
     *
     * Generated from protobuf field <code>string node_id = 1;</code>
     * @return string
     */
    public function getNodeId()
    {
        return $this->node_id;
    }

    /**
     * The id to a connected WorkflowNode which will be used as an input for current WorkflowNode.
     *
     * Generated from protobuf field <code>string node_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNodeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->node_id = $var;

        return $this;
    }

}

