<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Type of nodes that are ok for instances in this pool.
 * If both spot and on-demand are provided then the runner will be able to run on either
 * with a preference for spot until they are not available.
 *
 * Generated from protobuf message <code>clarifai.api.NodeCapacityType</code>
 */
class NodeCapacityType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.NodeCapacityType.CapacityType capacity_types = 1;</code>
     */
    private $capacity_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $capacity_types
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.NodeCapacityType.CapacityType capacity_types = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCapacityTypes()
    {
        return $this->capacity_types;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.NodeCapacityType.CapacityType capacity_types = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCapacityTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Clarifai\Api\NodeCapacityType\CapacityType::class);
        $this->capacity_types = $arr;

        return $this;
    }

}

