<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Password
 *
 * Generated from protobuf message <code>clarifai.api.Password</code>
 */
class Password extends \Google\Protobuf\Internal\Message
{
    /**
     * unencrypted password string
     *
     * Generated from protobuf field <code>string plaintext = 1;</code>
     */
    protected $plaintext = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $plaintext
     *           unencrypted password string
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * unencrypted password string
     *
     * Generated from protobuf field <code>string plaintext = 1;</code>
     * @return string
     */
    public function getPlaintext()
    {
        return $this->plaintext;
    }

    /**
     * unencrypted password string
     *
     * Generated from protobuf field <code>string plaintext = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaintext($var)
    {
        GPBUtil::checkString($var, True);
        $this->plaintext = $var;

        return $this;
    }

}

