<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.PipelineVersionRun</code>
 */
class PipelineVersionRun extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Pipeline Version associated with this run
     *
     * Generated from protobuf field <code>.clarifai.api.PipelineVersion pipeline_version = 2;</code>
     */
    protected $pipeline_version = null;
    /**
     * Nodepool(s) used for the Pipeline Version Run
     *
     * Generated from protobuf field <code>repeated .clarifai.api.Nodepool nodepools = 3;</code>
     */
    private $nodepools;
    /**
     * Orchestration Status for this run, supporting multiple orchestration systems
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationStatus orchestration_status = 4;</code>
     */
    protected $orchestration_status = null;
    /**
     * The user the pipeline belongs to
     *
     * Generated from protobuf field <code>string user_id = 5;</code>
     */
    protected $user_id = '';
    /**
     * The app the pipeline belongs to
     *
     * Generated from protobuf field <code>string app_id = 6;</code>
     */
    protected $app_id = '';
    /**
     * When the pipeline was created
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    protected $created_at = null;
    /**
     * When the pipeline was last modified
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp modified_at = 8;</code>
     */
    protected $modified_at = null;
    /**
     * Optional: Overrides to input arguments for the orchestration system.
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationArgsOverride input_args_override = 9;</code>
     */
    protected $input_args_override = null;
    /**
     * Final merged orchestration spec snapshot submitted to backend.
     * This field is read-only and cannot be set during creation.
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationSpec orchestration_spec = 10;</code>
     */
    protected $orchestration_spec = null;
    /**
     * When the pipeline run started executing (first JOB_RUNNING status)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 11;</code>
     */
    protected $started_at = null;
    /**
     * When the pipeline run finished executing (terminal status)  
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp ended_at = 12;</code>
     */
    protected $ended_at = null;
    /**
     * Total cumulative run duration excluding pause time
     *
     * Generated from protobuf field <code>.google.protobuf.Duration total_run_duration = 13;</code>
     */
    protected $total_run_duration = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Clarifai\Api\PipelineVersion $pipeline_version
     *           Pipeline Version associated with this run
     *     @type array<\Clarifai\Api\Nodepool>|\Google\Protobuf\Internal\RepeatedField $nodepools
     *           Nodepool(s) used for the Pipeline Version Run
     *     @type \Clarifai\Api\OrchestrationStatus $orchestration_status
     *           Orchestration Status for this run, supporting multiple orchestration systems
     *     @type string $user_id
     *           The user the pipeline belongs to
     *     @type string $app_id
     *           The app the pipeline belongs to
     *     @type \Google\Protobuf\Timestamp $created_at
     *           When the pipeline was created
     *     @type \Google\Protobuf\Timestamp $modified_at
     *           When the pipeline was last modified
     *     @type \Clarifai\Api\OrchestrationArgsOverride $input_args_override
     *           Optional: Overrides to input arguments for the orchestration system.
     *     @type \Clarifai\Api\OrchestrationSpec $orchestration_spec
     *           Final merged orchestration spec snapshot submitted to backend.
     *           This field is read-only and cannot be set during creation.
     *     @type \Google\Protobuf\Timestamp $started_at
     *           When the pipeline run started executing (first JOB_RUNNING status)
     *     @type \Google\Protobuf\Timestamp $ended_at
     *           When the pipeline run finished executing (terminal status)  
     *     @type \Google\Protobuf\Duration $total_run_duration
     *           Total cumulative run duration excluding pause time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Pipeline Version associated with this run
     *
     * Generated from protobuf field <code>.clarifai.api.PipelineVersion pipeline_version = 2;</code>
     * @return \Clarifai\Api\PipelineVersion|null
     */
    public function getPipelineVersion()
    {
        return $this->pipeline_version;
    }

    public function hasPipelineVersion()
    {
        return isset($this->pipeline_version);
    }

    public function clearPipelineVersion()
    {
        unset($this->pipeline_version);
    }

    /**
     * Pipeline Version associated with this run
     *
     * Generated from protobuf field <code>.clarifai.api.PipelineVersion pipeline_version = 2;</code>
     * @param \Clarifai\Api\PipelineVersion $var
     * @return $this
     */
    public function setPipelineVersion($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\PipelineVersion::class);
        $this->pipeline_version = $var;

        return $this;
    }

    /**
     * Nodepool(s) used for the Pipeline Version Run
     *
     * Generated from protobuf field <code>repeated .clarifai.api.Nodepool nodepools = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNodepools()
    {
        return $this->nodepools;
    }

    /**
     * Nodepool(s) used for the Pipeline Version Run
     *
     * Generated from protobuf field <code>repeated .clarifai.api.Nodepool nodepools = 3;</code>
     * @param array<\Clarifai\Api\Nodepool>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNodepools($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\Nodepool::class);
        $this->nodepools = $arr;

        return $this;
    }

    /**
     * Orchestration Status for this run, supporting multiple orchestration systems
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationStatus orchestration_status = 4;</code>
     * @return \Clarifai\Api\OrchestrationStatus|null
     */
    public function getOrchestrationStatus()
    {
        return $this->orchestration_status;
    }

    public function hasOrchestrationStatus()
    {
        return isset($this->orchestration_status);
    }

    public function clearOrchestrationStatus()
    {
        unset($this->orchestration_status);
    }

    /**
     * Orchestration Status for this run, supporting multiple orchestration systems
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationStatus orchestration_status = 4;</code>
     * @param \Clarifai\Api\OrchestrationStatus $var
     * @return $this
     */
    public function setOrchestrationStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\OrchestrationStatus::class);
        $this->orchestration_status = $var;

        return $this;
    }

    /**
     * The user the pipeline belongs to
     *
     * Generated from protobuf field <code>string user_id = 5;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * The user the pipeline belongs to
     *
     * Generated from protobuf field <code>string user_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * The app the pipeline belongs to
     *
     * Generated from protobuf field <code>string app_id = 6;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * The app the pipeline belongs to
     *
     * Generated from protobuf field <code>string app_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     * When the pipeline was created
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * When the pipeline was created
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * When the pipeline was last modified
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp modified_at = 8;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getModifiedAt()
    {
        return $this->modified_at;
    }

    public function hasModifiedAt()
    {
        return isset($this->modified_at);
    }

    public function clearModifiedAt()
    {
        unset($this->modified_at);
    }

    /**
     * When the pipeline was last modified
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp modified_at = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setModifiedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->modified_at = $var;

        return $this;
    }

    /**
     * Optional: Overrides to input arguments for the orchestration system.
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationArgsOverride input_args_override = 9;</code>
     * @return \Clarifai\Api\OrchestrationArgsOverride|null
     */
    public function getInputArgsOverride()
    {
        return $this->input_args_override;
    }

    public function hasInputArgsOverride()
    {
        return isset($this->input_args_override);
    }

    public function clearInputArgsOverride()
    {
        unset($this->input_args_override);
    }

    /**
     * Optional: Overrides to input arguments for the orchestration system.
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationArgsOverride input_args_override = 9;</code>
     * @param \Clarifai\Api\OrchestrationArgsOverride $var
     * @return $this
     */
    public function setInputArgsOverride($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\OrchestrationArgsOverride::class);
        $this->input_args_override = $var;

        return $this;
    }

    /**
     * Final merged orchestration spec snapshot submitted to backend.
     * This field is read-only and cannot be set during creation.
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationSpec orchestration_spec = 10;</code>
     * @return \Clarifai\Api\OrchestrationSpec|null
     */
    public function getOrchestrationSpec()
    {
        return $this->orchestration_spec;
    }

    public function hasOrchestrationSpec()
    {
        return isset($this->orchestration_spec);
    }

    public function clearOrchestrationSpec()
    {
        unset($this->orchestration_spec);
    }

    /**
     * Final merged orchestration spec snapshot submitted to backend.
     * This field is read-only and cannot be set during creation.
     *
     * Generated from protobuf field <code>.clarifai.api.OrchestrationSpec orchestration_spec = 10;</code>
     * @param \Clarifai\Api\OrchestrationSpec $var
     * @return $this
     */
    public function setOrchestrationSpec($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\OrchestrationSpec::class);
        $this->orchestration_spec = $var;

        return $this;
    }

    /**
     * When the pipeline run started executing (first JOB_RUNNING status)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 11;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    public function hasStartedAt()
    {
        return isset($this->started_at);
    }

    public function clearStartedAt()
    {
        unset($this->started_at);
    }

    /**
     * When the pipeline run started executing (first JOB_RUNNING status)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 11;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->started_at = $var;

        return $this;
    }

    /**
     * When the pipeline run finished executing (terminal status)  
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp ended_at = 12;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEndedAt()
    {
        return $this->ended_at;
    }

    public function hasEndedAt()
    {
        return isset($this->ended_at);
    }

    public function clearEndedAt()
    {
        unset($this->ended_at);
    }

    /**
     * When the pipeline run finished executing (terminal status)  
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp ended_at = 12;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->ended_at = $var;

        return $this;
    }

    /**
     * Total cumulative run duration excluding pause time
     *
     * Generated from protobuf field <code>.google.protobuf.Duration total_run_duration = 13;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getTotalRunDuration()
    {
        return $this->total_run_duration;
    }

    public function hasTotalRunDuration()
    {
        return isset($this->total_run_duration);
    }

    public function clearTotalRunDuration()
    {
        unset($this->total_run_duration);
    }

    /**
     * Total cumulative run duration excluding pause time
     *
     * Generated from protobuf field <code>.google.protobuf.Duration total_run_duration = 13;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setTotalRunDuration($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->total_run_duration = $var;

        return $this;
    }

}

