<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PostUserStarsRequest
 *
 * Generated from protobuf message <code>clarifai.api.PostUserStarsRequest</code>
 */
class PostUserStarsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * User stars to create (supports 1)
     *
     * Generated from protobuf field <code>repeated .clarifai.api.UserStar user_stars = 1;</code>
     */
    private $user_stars;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\UserStar[]|\Google\Protobuf\Internal\RepeatedField $user_stars
     *           User stars to create (supports 1)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * User stars to create (supports 1)
     *
     * Generated from protobuf field <code>repeated .clarifai.api.UserStar user_stars = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserStars()
    {
        return $this->user_stars;
    }

    /**
     * User stars to create (supports 1)
     *
     * Generated from protobuf field <code>repeated .clarifai.api.UserStar user_stars = 1;</code>
     * @param \Clarifai\Api\UserStar[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserStars($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\UserStar::class);
        $this->user_stars = $arr;

        return $this;
    }

}

