<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PostInstalledModuleVersionsRequest to install a module version into the app in the URL
 *
 * Generated from protobuf message <code>clarifai.api.PostInstalledModuleVersionsRequest</code>
 */
class PostInstalledModuleVersionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    protected $user_app_id = null;
    /**
     * This allows you to create one or more module by posting it to the API.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.InstalledModuleVersion installed_module_versions = 2;</code>
     */
    private $installed_module_versions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\UserAppIDSet $user_app_id
     *     @type array<\Clarifai\Api\InstalledModuleVersion>|\Google\Protobuf\Internal\RepeatedField $installed_module_versions
     *           This allows you to create one or more module by posting it to the API.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return \Clarifai\Api\UserAppIDSet|null
     */
    public function getUserAppId()
    {
        return $this->user_app_id;
    }

    public function hasUserAppId()
    {
        return isset($this->user_app_id);
    }

    public function clearUserAppId()
    {
        unset($this->user_app_id);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @param \Clarifai\Api\UserAppIDSet $var
     * @return $this
     */
    public function setUserAppId($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\UserAppIDSet::class);
        $this->user_app_id = $var;

        return $this;
    }

    /**
     * This allows you to create one or more module by posting it to the API.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.InstalledModuleVersion installed_module_versions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInstalledModuleVersions()
    {
        return $this->installed_module_versions;
    }

    /**
     * This allows you to create one or more module by posting it to the API.
     *
     * Generated from protobuf field <code>repeated .clarifai.api.InstalledModuleVersion installed_module_versions = 2;</code>
     * @param array<\Clarifai\Api\InstalledModuleVersion>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInstalledModuleVersions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Api\InstalledModuleVersion::class);
        $this->installed_module_versions = $arr;

        return $this;
    }

}

