<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PostSubscriptionRequest
 *
 * Generated from protobuf message <code>clarifai.api.PostSubscriptionRequest</code>
 */
class PostSubscriptionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string signup_code = 1;</code>
     */
    protected $signup_code = '';
    /**
     * Generated from protobuf field <code>.clarifai.api.Plan plan = 2;</code>
     */
    protected $plan = null;
    /**
     * Contains the user_id. Has to match the caller.
     *
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 3;</code>
     */
    protected $user_app_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signup_code
     *     @type \Clarifai\Api\Plan $plan
     *     @type \Clarifai\Api\UserAppIDSet $user_app_id
     *           Contains the user_id. Has to match the caller.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string signup_code = 1;</code>
     * @return string
     */
    public function getSignupCode()
    {
        return $this->signup_code;
    }

    /**
     * Generated from protobuf field <code>string signup_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignupCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->signup_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Plan plan = 2;</code>
     * @return \Clarifai\Api\Plan|null
     */
    public function getPlan()
    {
        return $this->plan;
    }

    public function hasPlan()
    {
        return isset($this->plan);
    }

    public function clearPlan()
    {
        unset($this->plan);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Plan plan = 2;</code>
     * @param \Clarifai\Api\Plan $var
     * @return $this
     */
    public function setPlan($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Plan::class);
        $this->plan = $var;

        return $this;
    }

    /**
     * Contains the user_id. Has to match the caller.
     *
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 3;</code>
     * @return \Clarifai\Api\UserAppIDSet|null
     */
    public function getUserAppId()
    {
        return $this->user_app_id;
    }

    public function hasUserAppId()
    {
        return isset($this->user_app_id);
    }

    public function clearUserAppId()
    {
        unset($this->user_app_id);
    }

    /**
     * Contains the user_id. Has to match the caller.
     *
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 3;</code>
     * @param \Clarifai\Api\UserAppIDSet $var
     * @return $this
     */
    public function setUserAppId($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\UserAppIDSet::class);
        $this->user_app_id = $var;

        return $this;
    }

}

