<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A region within the data.
 *
 * Generated from protobuf message <code>clarifai.api.Region</code>
 */
class Region extends \Google\Protobuf\Internal\Message
{
    /**
     * A unique id for the region.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * The details about the location of the region.
     *
     * Generated from protobuf field <code>.clarifai.api.RegionInfo region_info = 2;</code>
     */
    protected $region_info = null;
    /**
     * A recursive definition of the data within the Region. For example, this will contain
     * data.concepts if the region also has annotations or predictions of concepts within it.
     *
     * Generated from protobuf field <code>.clarifai.api.Data data = 3;</code>
     */
    protected $data = null;
    /**
     * This is the confidence score of the overall Region.
     *
     * Generated from protobuf field <code>float value = 4;</code>
     */
    protected $value = 0.0;
    /**
     * For tracking algorithsm and annotations we tie regions together with this track id.
     *
     * Generated from protobuf field <code>string track_id = 5;</code>
     */
    protected $track_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           A unique id for the region.
     *     @type \Clarifai\Api\RegionInfo $region_info
     *           The details about the location of the region.
     *     @type \Clarifai\Api\Data $data
     *           A recursive definition of the data within the Region. For example, this will contain
     *           data.concepts if the region also has annotations or predictions of concepts within it.
     *     @type float $value
     *           This is the confidence score of the overall Region.
     *     @type string $track_id
     *           For tracking algorithsm and annotations we tie regions together with this track id.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * A unique id for the region.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * A unique id for the region.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * The details about the location of the region.
     *
     * Generated from protobuf field <code>.clarifai.api.RegionInfo region_info = 2;</code>
     * @return \Clarifai\Api\RegionInfo|null
     */
    public function getRegionInfo()
    {
        return $this->region_info;
    }

    public function hasRegionInfo()
    {
        return isset($this->region_info);
    }

    public function clearRegionInfo()
    {
        unset($this->region_info);
    }

    /**
     * The details about the location of the region.
     *
     * Generated from protobuf field <code>.clarifai.api.RegionInfo region_info = 2;</code>
     * @param \Clarifai\Api\RegionInfo $var
     * @return $this
     */
    public function setRegionInfo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\RegionInfo::class);
        $this->region_info = $var;

        return $this;
    }

    /**
     * A recursive definition of the data within the Region. For example, this will contain
     * data.concepts if the region also has annotations or predictions of concepts within it.
     *
     * Generated from protobuf field <code>.clarifai.api.Data data = 3;</code>
     * @return \Clarifai\Api\Data|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * A recursive definition of the data within the Region. For example, this will contain
     * data.concepts if the region also has annotations or predictions of concepts within it.
     *
     * Generated from protobuf field <code>.clarifai.api.Data data = 3;</code>
     * @param \Clarifai\Api\Data $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Data::class);
        $this->data = $var;

        return $this;
    }

    /**
     * This is the confidence score of the overall Region.
     *
     * Generated from protobuf field <code>float value = 4;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * This is the confidence score of the overall Region.
     *
     * Generated from protobuf field <code>float value = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->value = $var;

        return $this;
    }

    /**
     * For tracking algorithsm and annotations we tie regions together with this track id.
     *
     * Generated from protobuf field <code>string track_id = 5;</code>
     * @return string
     */
    public function getTrackId()
    {
        return $this->track_id;
    }

    /**
     * For tracking algorithsm and annotations we tie regions together with this track id.
     *
     * Generated from protobuf field <code>string track_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackId($var)
    {
        GPBUtil::checkString($var, True);
        $this->track_id = $var;

        return $this;
    }

}

