<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RunnerReplicaTaskMetrics captures auto-annotation task metrics reported by an individual
 * runner replica. Each entry corresponds to a specific task running on a specific replica.
 *
 * Generated from protobuf message <code>clarifai.api.RunnerReplicaTaskMetrics</code>
 */
class RunnerReplicaTaskMetrics extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     */
    protected $task_id = '';
    /**
     * Time window these metrics cover.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     */
    protected $start_time = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     */
    protected $end_time = null;
    /**
     * Frame time range in milliseconds (nullable — absent when no frames have been processed yet).
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value start_frame_time = 4;</code>
     */
    protected $start_frame_time = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.UInt64Value end_frame_time = 5;</code>
     */
    protected $end_frame_time = null;
    /**
     * Frame counts.
     *
     * Generated from protobuf field <code>uint32 frames_processed = 10;</code>
     */
    protected $frames_processed = 0;
    /**
     * Generated from protobuf field <code>uint32 frames_dropped = 11;</code>
     */
    protected $frames_dropped = 0;
    /**
     * Generated from protobuf field <code>uint32 frames_skipped = 12;</code>
     */
    protected $frames_skipped = 0;
    /**
     * Annotation counts.
     *
     * Generated from protobuf field <code>uint32 annotations_uploaded = 20;</code>
     */
    protected $annotations_uploaded = 0;
    /**
     * Generated from protobuf field <code>uint32 annotations_failed = 21;</code>
     */
    protected $annotations_failed = 0;
    /**
     * Generated from protobuf field <code>uint32 batches_uploaded = 30;</code>
     */
    protected $batches_uploaded = 0;
    /**
     * Generated from protobuf field <code>uint32 batches_dropped = 31;</code>
     */
    protected $batches_dropped = 0;
    /**
     * Upload latency metrics (nullable — absent means not yet measured).
     *
     * Generated from protobuf field <code>.google.protobuf.Duration avg_upload_latency = 40;</code>
     */
    protected $avg_upload_latency = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_upload_latency = 41;</code>
     */
    protected $max_upload_latency = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration last_upload_latency = 42;</code>
     */
    protected $last_upload_latency = null;
    /**
     * Stream delay metrics (nullable — absent means not yet measured).
     *
     * Generated from protobuf field <code>.google.protobuf.Duration avg_stream_delay = 50;</code>
     */
    protected $avg_stream_delay = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_stream_delay = 51;</code>
     */
    protected $max_stream_delay = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration last_stream_delay = 52;</code>
     */
    protected $last_stream_delay = null;
    /**
     * Queue metrics.
     *
     * Generated from protobuf field <code>uint32 predict_queue_size = 60;</code>
     */
    protected $predict_queue_size = 0;
    /**
     * Generated from protobuf field <code>uint32 upload_queue_size = 61;</code>
     */
    protected $upload_queue_size = 0;
    /**
     * Current probability of dropping a frame (0.0 – 1.0).
     *
     * Generated from protobuf field <code>float current_frame_drop_chance = 70;</code>
     */
    protected $current_frame_drop_chance = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_id
     *     @type \Google\Protobuf\Timestamp $start_time
     *           Time window these metrics cover.
     *     @type \Google\Protobuf\Timestamp $end_time
     *     @type \Google\Protobuf\UInt64Value $start_frame_time
     *           Frame time range in milliseconds (nullable — absent when no frames have been processed yet).
     *     @type \Google\Protobuf\UInt64Value $end_frame_time
     *     @type int $frames_processed
     *           Frame counts.
     *     @type int $frames_dropped
     *     @type int $frames_skipped
     *     @type int $annotations_uploaded
     *           Annotation counts.
     *     @type int $annotations_failed
     *     @type int $batches_uploaded
     *     @type int $batches_dropped
     *     @type \Google\Protobuf\Duration $avg_upload_latency
     *           Upload latency metrics (nullable — absent means not yet measured).
     *     @type \Google\Protobuf\Duration $max_upload_latency
     *     @type \Google\Protobuf\Duration $last_upload_latency
     *     @type \Google\Protobuf\Duration $avg_stream_delay
     *           Stream delay metrics (nullable — absent means not yet measured).
     *     @type \Google\Protobuf\Duration $max_stream_delay
     *     @type \Google\Protobuf\Duration $last_stream_delay
     *     @type int $predict_queue_size
     *           Queue metrics.
     *     @type int $upload_queue_size
     *     @type float $current_frame_drop_chance
     *           Current probability of dropping a frame (0.0 – 1.0).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Time window these metrics cover.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * Time window these metrics cover.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    public function hasEndTime()
    {
        return isset($this->end_time);
    }

    public function clearEndTime()
    {
        unset($this->end_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Frame time range in milliseconds (nullable — absent when no frames have been processed yet).
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value start_frame_time = 4;</code>
     * @return \Google\Protobuf\UInt64Value|null
     */
    public function getStartFrameTime()
    {
        return $this->start_frame_time;
    }

    public function hasStartFrameTime()
    {
        return isset($this->start_frame_time);
    }

    public function clearStartFrameTime()
    {
        unset($this->start_frame_time);
    }

    /**
     * Returns the unboxed value from <code>getStartFrameTime()</code>

     * Frame time range in milliseconds (nullable — absent when no frames have been processed yet).
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value start_frame_time = 4;</code>
     * @return int|string|null
     */
    public function getStartFrameTimeUnwrapped()
    {
        return $this->readWrapperValue("start_frame_time");
    }

    /**
     * Frame time range in milliseconds (nullable — absent when no frames have been processed yet).
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value start_frame_time = 4;</code>
     * @param \Google\Protobuf\UInt64Value $var
     * @return $this
     */
    public function setStartFrameTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt64Value::class);
        $this->start_frame_time = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\UInt64Value object.

     * Frame time range in milliseconds (nullable — absent when no frames have been processed yet).
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value start_frame_time = 4;</code>
     * @param int|string|null $var
     * @return $this
     */
    public function setStartFrameTimeUnwrapped($var)
    {
        $this->writeWrapperValue("start_frame_time", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt64Value end_frame_time = 5;</code>
     * @return \Google\Protobuf\UInt64Value|null
     */
    public function getEndFrameTime()
    {
        return $this->end_frame_time;
    }

    public function hasEndFrameTime()
    {
        return isset($this->end_frame_time);
    }

    public function clearEndFrameTime()
    {
        unset($this->end_frame_time);
    }

    /**
     * Returns the unboxed value from <code>getEndFrameTime()</code>

     * Generated from protobuf field <code>.google.protobuf.UInt64Value end_frame_time = 5;</code>
     * @return int|string|null
     */
    public function getEndFrameTimeUnwrapped()
    {
        return $this->readWrapperValue("end_frame_time");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt64Value end_frame_time = 5;</code>
     * @param \Google\Protobuf\UInt64Value $var
     * @return $this
     */
    public function setEndFrameTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt64Value::class);
        $this->end_frame_time = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\UInt64Value object.

     * Generated from protobuf field <code>.google.protobuf.UInt64Value end_frame_time = 5;</code>
     * @param int|string|null $var
     * @return $this
     */
    public function setEndFrameTimeUnwrapped($var)
    {
        $this->writeWrapperValue("end_frame_time", $var);
        return $this;}

    /**
     * Frame counts.
     *
     * Generated from protobuf field <code>uint32 frames_processed = 10;</code>
     * @return int
     */
    public function getFramesProcessed()
    {
        return $this->frames_processed;
    }

    /**
     * Frame counts.
     *
     * Generated from protobuf field <code>uint32 frames_processed = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setFramesProcessed($var)
    {
        GPBUtil::checkUint32($var);
        $this->frames_processed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 frames_dropped = 11;</code>
     * @return int
     */
    public function getFramesDropped()
    {
        return $this->frames_dropped;
    }

    /**
     * Generated from protobuf field <code>uint32 frames_dropped = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setFramesDropped($var)
    {
        GPBUtil::checkUint32($var);
        $this->frames_dropped = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 frames_skipped = 12;</code>
     * @return int
     */
    public function getFramesSkipped()
    {
        return $this->frames_skipped;
    }

    /**
     * Generated from protobuf field <code>uint32 frames_skipped = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setFramesSkipped($var)
    {
        GPBUtil::checkUint32($var);
        $this->frames_skipped = $var;

        return $this;
    }

    /**
     * Annotation counts.
     *
     * Generated from protobuf field <code>uint32 annotations_uploaded = 20;</code>
     * @return int
     */
    public function getAnnotationsUploaded()
    {
        return $this->annotations_uploaded;
    }

    /**
     * Annotation counts.
     *
     * Generated from protobuf field <code>uint32 annotations_uploaded = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setAnnotationsUploaded($var)
    {
        GPBUtil::checkUint32($var);
        $this->annotations_uploaded = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 annotations_failed = 21;</code>
     * @return int
     */
    public function getAnnotationsFailed()
    {
        return $this->annotations_failed;
    }

    /**
     * Generated from protobuf field <code>uint32 annotations_failed = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setAnnotationsFailed($var)
    {
        GPBUtil::checkUint32($var);
        $this->annotations_failed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 batches_uploaded = 30;</code>
     * @return int
     */
    public function getBatchesUploaded()
    {
        return $this->batches_uploaded;
    }

    /**
     * Generated from protobuf field <code>uint32 batches_uploaded = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchesUploaded($var)
    {
        GPBUtil::checkUint32($var);
        $this->batches_uploaded = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 batches_dropped = 31;</code>
     * @return int
     */
    public function getBatchesDropped()
    {
        return $this->batches_dropped;
    }

    /**
     * Generated from protobuf field <code>uint32 batches_dropped = 31;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchesDropped($var)
    {
        GPBUtil::checkUint32($var);
        $this->batches_dropped = $var;

        return $this;
    }

    /**
     * Upload latency metrics (nullable — absent means not yet measured).
     *
     * Generated from protobuf field <code>.google.protobuf.Duration avg_upload_latency = 40;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getAvgUploadLatency()
    {
        return $this->avg_upload_latency;
    }

    public function hasAvgUploadLatency()
    {
        return isset($this->avg_upload_latency);
    }

    public function clearAvgUploadLatency()
    {
        unset($this->avg_upload_latency);
    }

    /**
     * Upload latency metrics (nullable — absent means not yet measured).
     *
     * Generated from protobuf field <code>.google.protobuf.Duration avg_upload_latency = 40;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setAvgUploadLatency($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->avg_upload_latency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_upload_latency = 41;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getMaxUploadLatency()
    {
        return $this->max_upload_latency;
    }

    public function hasMaxUploadLatency()
    {
        return isset($this->max_upload_latency);
    }

    public function clearMaxUploadLatency()
    {
        unset($this->max_upload_latency);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_upload_latency = 41;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setMaxUploadLatency($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->max_upload_latency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration last_upload_latency = 42;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getLastUploadLatency()
    {
        return $this->last_upload_latency;
    }

    public function hasLastUploadLatency()
    {
        return isset($this->last_upload_latency);
    }

    public function clearLastUploadLatency()
    {
        unset($this->last_upload_latency);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration last_upload_latency = 42;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setLastUploadLatency($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->last_upload_latency = $var;

        return $this;
    }

    /**
     * Stream delay metrics (nullable — absent means not yet measured).
     *
     * Generated from protobuf field <code>.google.protobuf.Duration avg_stream_delay = 50;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getAvgStreamDelay()
    {
        return $this->avg_stream_delay;
    }

    public function hasAvgStreamDelay()
    {
        return isset($this->avg_stream_delay);
    }

    public function clearAvgStreamDelay()
    {
        unset($this->avg_stream_delay);
    }

    /**
     * Stream delay metrics (nullable — absent means not yet measured).
     *
     * Generated from protobuf field <code>.google.protobuf.Duration avg_stream_delay = 50;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setAvgStreamDelay($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->avg_stream_delay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_stream_delay = 51;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getMaxStreamDelay()
    {
        return $this->max_stream_delay;
    }

    public function hasMaxStreamDelay()
    {
        return isset($this->max_stream_delay);
    }

    public function clearMaxStreamDelay()
    {
        unset($this->max_stream_delay);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_stream_delay = 51;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setMaxStreamDelay($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->max_stream_delay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration last_stream_delay = 52;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getLastStreamDelay()
    {
        return $this->last_stream_delay;
    }

    public function hasLastStreamDelay()
    {
        return isset($this->last_stream_delay);
    }

    public function clearLastStreamDelay()
    {
        unset($this->last_stream_delay);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration last_stream_delay = 52;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setLastStreamDelay($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->last_stream_delay = $var;

        return $this;
    }

    /**
     * Queue metrics.
     *
     * Generated from protobuf field <code>uint32 predict_queue_size = 60;</code>
     * @return int
     */
    public function getPredictQueueSize()
    {
        return $this->predict_queue_size;
    }

    /**
     * Queue metrics.
     *
     * Generated from protobuf field <code>uint32 predict_queue_size = 60;</code>
     * @param int $var
     * @return $this
     */
    public function setPredictQueueSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->predict_queue_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 upload_queue_size = 61;</code>
     * @return int
     */
    public function getUploadQueueSize()
    {
        return $this->upload_queue_size;
    }

    /**
     * Generated from protobuf field <code>uint32 upload_queue_size = 61;</code>
     * @param int $var
     * @return $this
     */
    public function setUploadQueueSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->upload_queue_size = $var;

        return $this;
    }

    /**
     * Current probability of dropping a frame (0.0 – 1.0).
     *
     * Generated from protobuf field <code>float current_frame_drop_chance = 70;</code>
     * @return float
     */
    public function getCurrentFrameDropChance()
    {
        return $this->current_frame_drop_chance;
    }

    /**
     * Current probability of dropping a frame (0.0 – 1.0).
     *
     * Generated from protobuf field <code>float current_frame_drop_chance = 70;</code>
     * @param float $var
     * @return $this
     */
    public function setCurrentFrameDropChance($var)
    {
        GPBUtil::checkFloat($var);
        $this->current_frame_drop_chance = $var;

        return $this;
    }

}

