<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RunnerMetrics captures metrics and status for a Runner's underlying k8s deployment.
 * This allows tracking of deployment health, replica counts, and other relevant metrics.
 *
 * Generated from protobuf message <code>clarifai.api.RunnerMetrics</code>
 */
class RunnerMetrics extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 pods_total = 1;</code>
     */
    protected $pods_total = 0;
    /**
     * Generated from protobuf field <code>uint32 pods_running = 2;</code>
     */
    protected $pods_running = 0;
    /**
     * Cumulative total time (in seconds) that pods have been running for this runner.
     * This accumulates across scale-up/down cycles and is reported by the agent.
     *
     * Generated from protobuf field <code>uint32 total_pods_running_time_s = 3;</code>
     */
    protected $total_pods_running_time_s = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pods_total
     *     @type int $pods_running
     *     @type int $total_pods_running_time_s
     *           Cumulative total time (in seconds) that pods have been running for this runner.
     *           This accumulates across scale-up/down cycles and is reported by the agent.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 pods_total = 1;</code>
     * @return int
     */
    public function getPodsTotal()
    {
        return $this->pods_total;
    }

    /**
     * Generated from protobuf field <code>uint32 pods_total = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPodsTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->pods_total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pods_running = 2;</code>
     * @return int
     */
    public function getPodsRunning()
    {
        return $this->pods_running;
    }

    /**
     * Generated from protobuf field <code>uint32 pods_running = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPodsRunning($var)
    {
        GPBUtil::checkUint32($var);
        $this->pods_running = $var;

        return $this;
    }

    /**
     * Cumulative total time (in seconds) that pods have been running for this runner.
     * This accumulates across scale-up/down cycles and is reported by the agent.
     *
     * Generated from protobuf field <code>uint32 total_pods_running_time_s = 3;</code>
     * @return int
     */
    public function getTotalPodsRunningTimeS()
    {
        return $this->total_pods_running_time_s;
    }

    /**
     * Cumulative total time (in seconds) that pods have been running for this runner.
     * This accumulates across scale-up/down cycles and is reported by the agent.
     *
     * Generated from protobuf field <code>uint32 total_pods_running_time_s = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalPodsRunningTimeS($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_pods_running_time_s = $var;

        return $this;
    }

}

