<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.RunnerItemOutput</code>
 */
class RunnerItemOutput extends \Google\Protobuf\Internal\Message
{
    protected $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\MultiOutputResponse $multi_output_response
     *           The output of a model prediction request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * The output of a model prediction request.
     *
     * Generated from protobuf field <code>.clarifai.api.MultiOutputResponse multi_output_response = 1;</code>
     * @return \Clarifai\Api\MultiOutputResponse|null
     */
    public function getMultiOutputResponse()
    {
        return $this->readOneof(1);
    }

    public function hasMultiOutputResponse()
    {
        return $this->hasOneof(1);
    }

    /**
     * The output of a model prediction request.
     *
     * Generated from protobuf field <code>.clarifai.api.MultiOutputResponse multi_output_response = 1;</code>
     * @param \Clarifai\Api\MultiOutputResponse $var
     * @return $this
     */
    public function setMultiOutputResponse($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\MultiOutputResponse::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

