<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SingleFindDuplicateAnnotationsJobResponse
 *
 * Generated from protobuf message <code>clarifai.api.SingleFindDuplicateAnnotationsJobResponse</code>
 */
class SingleFindDuplicateAnnotationsJobResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.FindDuplicateAnnotationsJob find_duplicate_annotations_job = 2;</code>
     */
    protected $find_duplicate_annotations_job = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\Status\Status $status
     *     @type \Clarifai\Api\FindDuplicateAnnotationsJob $find_duplicate_annotations_job
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Api\Status\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Api\Status\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Status\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FindDuplicateAnnotationsJob find_duplicate_annotations_job = 2;</code>
     * @return \Clarifai\Api\FindDuplicateAnnotationsJob|null
     */
    public function getFindDuplicateAnnotationsJob()
    {
        return $this->find_duplicate_annotations_job;
    }

    public function hasFindDuplicateAnnotationsJob()
    {
        return isset($this->find_duplicate_annotations_job);
    }

    public function clearFindDuplicateAnnotationsJob()
    {
        unset($this->find_duplicate_annotations_job);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FindDuplicateAnnotationsJob find_duplicate_annotations_job = 2;</code>
     * @param \Clarifai\Api\FindDuplicateAnnotationsJob $var
     * @return $this
     */
    public function setFindDuplicateAnnotationsJob($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\FindDuplicateAnnotationsJob::class);
        $this->find_duplicate_annotations_job = $var;

        return $this;
    }

}

