<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response with a label order.
 *
 * Generated from protobuf message <code>clarifai.api.SingleLabelOrderResponse</code>
 */
class SingleLabelOrderResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.LabelOrder label_order = 2;</code>
     */
    protected $label_order = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\Status\Status $status
     *     @type \Clarifai\Api\LabelOrder $label_order
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Api\Status\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Api\Status\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Status\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.LabelOrder label_order = 2;</code>
     * @return \Clarifai\Api\LabelOrder|null
     */
    public function getLabelOrder()
    {
        return $this->label_order;
    }

    public function hasLabelOrder()
    {
        return isset($this->label_order);
    }

    public function clearLabelOrder()
    {
        unset($this->label_order);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.LabelOrder label_order = 2;</code>
     * @param \Clarifai\Api\LabelOrder $var
     * @return $this
     */
    public function setLabelOrder($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\LabelOrder::class);
        $this->label_order = $var;

        return $this;
    }

}

