<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/service.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SingleNotificationResponse
 *
 * Generated from protobuf message <code>clarifai.api.SingleWebNotificationResponse</code>
 */
class SingleWebNotificationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The response status.
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Notification
     *
     * Generated from protobuf field <code>.clarifai.api.WebNotification notification = 2;</code>
     */
    protected $notification = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Clarifai\Api\Status\Status $status
     *           The response status.
     *     @type \Clarifai\Api\WebNotification $notification
     *           Notification
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * The response status.
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Api\Status\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * The response status.
     *
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Api\Status\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Status\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Notification
     *
     * Generated from protobuf field <code>.clarifai.api.WebNotification notification = 2;</code>
     * @return \Clarifai\Api\WebNotification|null
     */
    public function getNotification()
    {
        return $this->notification;
    }

    public function hasNotification()
    {
        return isset($this->notification);
    }

    public function clearNotification()
    {
        unset($this->notification);
    }

    /**
     * Notification
     *
     * Generated from protobuf field <code>.clarifai.api.WebNotification notification = 2;</code>
     * @param \Clarifai\Api\WebNotification $var
     * @return $this
     */
    public function setNotification($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\WebNotification::class);
        $this->notification = $var;

        return $this;
    }

}

