<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * StatValue
 *
 * Generated from protobuf message <code>clarifai.api.StatValue</code>
 */
class StatValue extends \Google\Protobuf\Internal\Message
{
    /**
     * The time of the event. Defaults to now().
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 1;</code>
     */
    protected $time = null;
    /**
     * A value for the metric you're recording.
     *
     * Generated from protobuf field <code>float value = 2;</code>
     */
    protected $value = 0.0;
    /**
     * List of tags to attach to this stat. Each should contain one colon so that the first part will
     * be used as a tag group while the second being the tag itself. For example: ["task_id:a",
     * "worker_id:1"]. These tag groups like "task_id" or "worker_id" are important for aggregating
     * values in the StatValueAggregateQuery.
     *
     * Generated from protobuf field <code>repeated string tags = 3;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $time
     *           The time of the event. Defaults to now().
     *     @type float $value
     *           A value for the metric you're recording.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $tags
     *           List of tags to attach to this stat. Each should contain one colon so that the first part will
     *           be used as a tag group while the second being the tag itself. For example: ["task_id:a",
     *           "worker_id:1"]. These tag groups like "task_id" or "worker_id" are important for aggregating
     *           values in the StatValueAggregateQuery.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * The time of the event. Defaults to now().
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTime()
    {
        return $this->time;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * The time of the event. Defaults to now().
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->time = $var;

        return $this;
    }

    /**
     * A value for the metric you're recording.
     *
     * Generated from protobuf field <code>float value = 2;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * A value for the metric you're recording.
     *
     * Generated from protobuf field <code>float value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->value = $var;

        return $this;
    }

    /**
     * List of tags to attach to this stat. Each should contain one colon so that the first part will
     * be used as a tag group while the second being the tag itself. For example: ["task_id:a",
     * "worker_id:1"]. These tag groups like "task_id" or "worker_id" are important for aggregating
     * values in the StatValueAggregateQuery.
     *
     * Generated from protobuf field <code>repeated string tags = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * List of tags to attach to this stat. Each should contain one colon so that the first part will
     * be used as a tag group while the second being the tag itself. For example: ["task_id:a",
     * "worker_id:1"]. These tag groups like "task_id" or "worker_id" are important for aggregating
     * values in the StatValueAggregateQuery.
     *
     * Generated from protobuf field <code>repeated string tags = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

