<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Track proto encodes information of a track over a number of frames
 *
 * Generated from protobuf message <code>clarifai.api.Track</code>
 */
class Track extends \Google\Protobuf\Internal\Message
{
    /**
     * track id
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * This is a recursive definition which can contain all the concepts,
     * embeddings, etc. that are computed within this track.
     *
     * Generated from protobuf field <code>.clarifai.api.Data data = 2;</code>
     */
    protected $data = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.TimeInfo time_info = 4;</code>
     */
    protected $time_info = null;
    /**
     * Generated from protobuf field <code>float quality = 5;</code>
     */
    protected $quality = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           track id
     *     @type \Clarifai\Api\Data $data
     *           This is a recursive definition which can contain all the concepts,
     *           embeddings, etc. that are computed within this track.
     *     @type \Clarifai\Api\TimeInfo $time_info
     *     @type float $quality
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Clarifai\Api\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * track id
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * track id
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * This is a recursive definition which can contain all the concepts,
     * embeddings, etc. that are computed within this track.
     *
     * Generated from protobuf field <code>.clarifai.api.Data data = 2;</code>
     * @return \Clarifai\Api\Data|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * This is a recursive definition which can contain all the concepts,
     * embeddings, etc. that are computed within this track.
     *
     * Generated from protobuf field <code>.clarifai.api.Data data = 2;</code>
     * @param \Clarifai\Api\Data $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\Data::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.TimeInfo time_info = 4;</code>
     * @return \Clarifai\Api\TimeInfo|null
     */
    public function getTimeInfo()
    {
        return $this->time_info;
    }

    public function hasTimeInfo()
    {
        return isset($this->time_info);
    }

    public function clearTimeInfo()
    {
        unset($this->time_info);
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.TimeInfo time_info = 4;</code>
     * @param \Clarifai\Api\TimeInfo $var
     * @return $this
     */
    public function setTimeInfo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Api\TimeInfo::class);
        $this->time_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float quality = 5;</code>
     * @return float
     */
    public function getQuality()
    {
        return $this->quality;
    }

    /**
     * Generated from protobuf field <code>float quality = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setQuality($var)
    {
        GPBUtil::checkFloat($var);
        $this->quality = $var;

        return $this;
    }

}

