<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api;

use UnexpectedValueException;

/**
 * Protobuf type <code>clarifai.api.WorkflowModelUseCase</code>
 */
class WorkflowModelUseCase
{
    /**
     * Generated from protobuf enum <code>WORKFLOW_MODEL_USE_CASE_NOT_SET = 0;</code>
     */
    const WORKFLOW_MODEL_USE_CASE_NOT_SET = 0;
    /**
     * Classifier models without a detector parent (recursive check) in a workflow
     * are used for classification.
     *
     * Generated from protobuf enum <code>CLASSIFICATION = 1;</code>
     */
    const CLASSIFICATION = 1;
    /**
     * Detector models in a workflow are used for detection.
     * Classifier models that run after a detector model are also used for detection.
     *
     * Generated from protobuf enum <code>DETECTION = 2;</code>
     */
    const DETECTION = 2;

    private static $valueToName = [
        self::WORKFLOW_MODEL_USE_CASE_NOT_SET => 'WORKFLOW_MODEL_USE_CASE_NOT_SET',
        self::CLASSIFICATION => 'CLASSIFICATION',
        self::DETECTION => 'DETECTION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

