<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/resources.proto

namespace Clarifai\Api\State;

use UnexpectedValueException;

/**
 * Protobuf type <code>clarifai.api.State.RunningEnvironment</code>
 */
class RunningEnvironment
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_RUNNING_ENVIRONMENT = 0;</code>
     */
    const UNKNOWN_RUNNING_ENVIRONMENT = 0;
    /**
     * Generated from protobuf enum <code>DEVELOPMENT = 1;</code>
     */
    const DEVELOPMENT = 1;
    /**
     * Generated from protobuf enum <code>PRODUCTION = 2;</code>
     */
    const PRODUCTION = 2;

    private static $valueToName = [
        self::UNKNOWN_RUNNING_ENVIRONMENT => 'UNKNOWN_RUNNING_ENVIRONMENT',
        self::DEVELOPMENT => 'DEVELOPMENT',
        self::PRODUCTION => 'PRODUCTION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RunningEnvironment::class, \Clarifai\Api\State_RunningEnvironment::class);

