name: Publish package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9a-zA-Z]+'  # Matches 1.2.3, 1.2.3alpha1 etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Packagist.org
        env:
          PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN}}
        run: |
          curl --fail -L -XPOST -H'content-type:application/json' \
            "https://packagist.org/api/update-package?username=clarifai&apiToken=${PACKAGIST_API_TOKEN}" \
            -d'{"repository":{"url":"https://packagist.org/packages/clarifai/clarifai-php-grpc"}}'
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Slack Notify
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON: "https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png"
          SLACK_USERNAME: "GitHub Alerts"
          SLACK_CHANNEL: "#grpc-client-repo-alerts"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Publish failure"
          SLACK_FOOTER: "Clarifai PHP GRPC Repo"
